#!/bin/bash

## Description: Run all linting tools on files
## Usage: lint-all [--files|-f "file1 file2"] [--all|-a]
## Example: "ddev lint-all" (checks changed files)
##          "ddev lint-all -f 'file1.php file2.js'" (checks specific files)
##          "ddev lint-all --all" (checks all custom files)
## ExecRaw: true

echo "Running all linting tools..."

echo -e "\n🔍 Running PHP CodeSniffer..."
ddev dev-phpcs "$@" || exit $?

echo -e "\n🔍 Running ESLint..."
ddev dev-eslint "$@" || exit $?

echo -e "\n🔍 Running Stylelint..."
ddev dev-stylelint "$@" || exit $?

echo -e "\n🔍 Running TwigCS Fixer..."
ddev dev-twigcs "$@" || exit $?

echo -e "\n🔍 Running CSpell..."
ddev dev-cspell "$@" || exit $?

echo -e "\n🔍 Running PHPStan..."
ddev dev-phpstan "$@" || exit $?