#!/bin/bash

## #ddev-generated
# Fail on errors
set -euo pipefail

# The files to check are passed as arguments to this script
FILES_TO_CHECK="$@"

if [ -z "$FILES_TO_CHECK" ]; then
  echo "❌ No files provided to check"
  exit 1
fi

echo "Spell Checking:"
echo "$FILES_TO_CHECK" | tr ' ' '\n'

node ./node_modules/cspell/bin.js --config .cspell.json --color $FILES_TO_CHECK
