#!/bin/bash

## #ddev-generated
# Fail on errors
set -euo pipefail

# The files to check are passed as arguments to this script
FILES_TO_CHECK="$@"

if [ -z "$FILES_TO_CHECK" ]; then
  echo "❌ No files provided to check"
  exit 1
fi

echo "🔍 Running TwigCS Fixer on files:"
echo "$FILES_TO_CHECK" | tr ' ' '\n'

./bin/twig-cs-fixer lint $FILES_TO_CHECK