#!/bin/bash

## #ddev-generated
## Description: Run ESLint on custom JS files
# Fail on errors
set -euo pipefail

# The files to check are passed as arguments to this script
FILES_TO_CHECK="$@"

if [ -z "$FILES_TO_CHECK" ]; then
  echo "❌ No files provided to check"
  exit 1
fi

echo "🔍 Running JS Linting on files:"
echo "$FILES_TO_CHECK" | tr ' ' '\n'

node ./node_modules/eslint/bin/eslint.js --config=docroot/core/.eslintrc.json --no-eslintrc -f stylish --color $FILES_TO_CHECK