#!/bin/bash

# Fail on errors
set -euo pipefail

# The files to check are passed as arguments to this script
FILES_TO_CHECK="$@"

if [ -z "$FILES_TO_CHECK" ]; then
  echo "❌ No files provided to check"
  exit 1
fi

echo "🔍 Running Stylelint on files:"
echo "$FILES_TO_CHECK" | tr ' ' '\n'

node ./node_modules/stylelint/bin/stylelint.mjs --config ./.stylelintrc.json --color $FILES_TO_CHECK
