#!/bin/bash

set -e

PHP_CHANGED_FILES=$(git diff --name-only --diff-filter=dr origin/$BITBUCKET_PR_DESTINATION_BRANCH...$BITBUCKET_BRANCH | grep -E 'docroot/(modules|themes)/custom/.*\.(php|module)$' | tr '\n' ' ')
JS_CHANGED_FILES=$(git diff --name-only --diff-filter=dr origin/$BITBUCKET_PR_DESTINATION_BRANCH...$BITBUCKET_BRANCH | grep -E 'docroot/(modules|themes)/custom/.*\.(js)$' | tr '\n' ' ')
STYLE_CHANGED_FILES=$(git diff --name-only --diff-filter=dr origin/$BITBUCKET_PR_DESTINATION_BRANCH...$BITBUCKET_BRANCH | grep -E 'docroot/(modules|themes)/custom/.*\.(css)$' | tr '\n' ' ')
TWIG_CHANGED_FILES=$(git diff --name-only --diff-filter=dr origin/$BITBUCKET_PR_DESTINATION_BRANCH...$BITBUCKET_BRANCH | grep -E 'docroot/(modules|themes)/custom/.*\.(twig)$' | tr '\n' ' ')
TEXT_CHANGED_FILES=$(git diff --name-only --diff-filter=dr origin/$BITBUCKET_PR_DESTINATION_BRANCH...$BITBUCKET_BRANCH | grep -E 'docroot/(modules)/custom/.*\.(php|module|js|twig|yml|yaml|json|css|scss|sass|md|txt)$' | tr '\n' ' ')

echo "Running linting tools..."

# PHP Linting
if [ -z "$PHP_CHANGED_FILES" ]; then
echo "No relevant files changed. Skipping PHP Coding Standards (PHPCS) step."
else
echo \"$PHP_CHANGED_FILES\" | tr ' ' '\n'
composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
composer require drupal/coder dealerdirect/phpcodesniffer-composer-installer
phpcs --version
phpcs -- -s --colors --standard=Drupal --report-full --report-summary $PHP_CHANGED_FILES
phpcs -- -s --colors --standard=DrupalPractice --report-full --report-summary $PHP_CHANGED_FILES
fi

# JS Linting
if [ -z "$JS_CHANGED_FILES" ]; then
echo "No relevant files changed. Skipping JavaScript Linting (ESLint) step."
else
echo \"$JS_CHANGED_FILES\" | tr ' ' '\n'
yarn --modules-folder /var/www/html/node_modules --cwd /var/www/html/docroot/core/ install
node ./node_modules/eslint/bin/eslint.js --version
node ./node_modules/eslint/bin/eslint.js --config=docroot/core/.eslintrc.json --no-eslintrc -f stylish --color $JS_CHANGED_FILES
fi

# CSS Linting
if [ -z "$STYLE_CHANGED_FILES" ]; then
echo "No relevant files changed. Skipping CSS Linting (Stylelint) step."
else
echo \"$STYLE_CHANGED_FILES\" | tr ' ' '\n'
yarn --modules-folder /var/www/html/node_modules --cwd /var/www/html/docroot/core/ install
node ./node_modules/stylelint/bin/stylelint.mjs --version
node ./node_modules/stylelint/bin/stylelint.mjs --config ./.stylelintrc.json  --color  $STYLE_CHANGED_FILES
fi

# Twig Linting
if [ -z "$TWIG_CHANGED_FILES" ]; then
echo "No relevant files changed. Skipping Twig Linting (Twig-CS-Fixer) step."
else
echo \"$TWIG_CHANGED_FILES\" | tr ' ' '\n'
composer config allow-plugins.vincentlanglet/twig-cs-fixer true
composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
composer require drupal/coder vincentlanglet/twig-cs-fixer
./bin/twig-cs-fixer --version
./bin/twig-cs-fixer lint $TWIG_CHANGED_FILES
fi

# Spell Checking
if [ -z "$TEXT_CHANGED_FILES" ]; then
echo "No relevant files changed. Skipping Spell Checking (CSpell) step."
else
echo \"$TEXT_CHANGED_FILES\" | tr ' ' '\n'
yarn --modules-folder /var/www/html/node_modules --cwd /var/www/html/docroot/core/ install
node ./node_modules/cspell/bin.mjs --version
node ./node_modules/cspell/bin.mjs --config .cspell.json --color $TEXT_CHANGED_FILES
fi
