#!/bin/bash
#ddev-generated

## Description: Open an interactive Cypress window
##              https://docs.cypress.io/guides/guides/command-line#cypress-open
## Usage: cypress-ui [arguments]
## Example: "ddev cypress-ui --config cypress.json"

cypress open --project . "$@"
