#!/bin/bash
#ddev-generated

## Description: Install npm packages in the Cypress container
## Usage: cypress-install
## Example: "ddev cypress-install"

export npm_config_cache=/tmp/.npm
npm install @badeball/cypress-cucumber-preprocessor --include=optional
npm install @bahmutov/cypress-esbuild-preprocessor --include=optional
npm install cypress-file-upload --include=optional
npm install cypress-mochawesome-reporter --include=optional